nginx-s3-proxy:
  image: gallna/nginx.s3
  ports:
    - 80:80
  environment:
    AWS_REGION: ${AWS_DEFAULT_REGION}
    AWS_S3_PREFIX: ${AWS_S3_PREFIX}
    AWS_S3_BUCKET: ${AWS_S3_BUCKET}
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
